name: spyder

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.14.*
  - numpy
  - pandas
  - scipy
  - matplotlib
  - spyder=6.1.*
  - numba
  - pathlib
  - seaborn
  - tqdm

  - pip

  - pip:
    - curvefitgui
    - tk
  
